### ISSUE TITLE
【compatibility】The position of 3D weapons and equipment on ornaments will become very strange.

### ISSUE THREAD

**Issue by GalaxyZEROX** [KermitEmperor/CuriosBackSlot#5]
3D weapons (some guns MOD and other MOD weapons) will be installed in ornaments in strange positions (some weapons will become several times larger).

Suggestion: You can change the  in the weapon display on the back to "items that are worn on your head (refer to the scabbard equipment effect in" Arsenal Core”MOD) ".

**Comment by KermitEmperor** [comment]
Duplicate of #2
