### ISSUE TITLE
Shift clicking items into the curios menu makes them go into the weapon slot if not already full

### ISSUE THREAD

**Issue by Nicodemus111** [KermitEmperor/CuriosBackSlot#7]
If you shift click any curio into the curios menu it will go into the weapon slot first and the intended slot only if the weapon slot is full. This behavior could be fixed by changing the slot to be the lowest order in the menu (preferably like 999 for compatibility), or adding a config to disallow items with curio slot data from being added to the weapon slot.

**Comment by KermitEmperor** [comment]
fixed in 
1.0.3-nc (1.18.2)
2.0.5-nc (1.19.2)
3.0.5-nc (1.19.4)
4.0.6-nc (1.20.1)

and future versions
