### ISSUE TITLE
Compatibility wiht Simply Swords

### ISSUE THREAD

**Issue by Vandorsolyom** [KermitEmperor/CuriosBackSlot#8]
The simply swords mod seems to be broken at the moment. Is it possible to add support for it?

**Comment by OniFearr** [comment]
Its not a issue with the mod, its a issue with how simply swords are placed on the character. I've created a resource pack to fix this you can find it here: https://modrinth.com/resourcepack/simply-swords-+-weapon-back-slot-fix
